### ISSUE TITLE
Remember last location in the list of videos?

### ISSUE THREAD

**Issue by leftlane** [liquidweb/wp101plugin#53]
Is there a way to ‘remember’ the user’s place in the massive list of videos? 

When a user leaves, then returns to the videos, they're back at the first video in the WordPress 101 course. This is highly likely to occur, for example, when a user leaves the videos to go practice what they've learned. 

It's made even more confusing if a user is watching a video in one of the other courses (WooCommerce, Jetpack, etc.). When they return, that course is minimized/collapsed, and they're back at the top of WordPress 101 again.

Ideally, we'd return a user to the last video they watched. But, if we can at least indicate videos that have not yet been viewed by making their titles appear in bold, that would be a huge help to users.

Unwatched = bold title. Once watched = normal title.

**Comment by stevegrunwell** [comment]
The plugin contains the necessary logic to read the video to load from the URL and update the UI accordingly, so it wouldn't take much more to drop the last video viewed in `window.sessionStorage` (meaning it only persists the latest video locally) and, if no other video is specified in the hash, load that video.

As far as tracking viewed videos, this is slightly more complicated (we need to store this in user-meta, ensuring that a viewing of the video on one device will be reflected on another). Still certainly do-able, though.

**Comment by leftlane** [comment]
Saving the last video viewed will be a huge help. For now, let's skip tracking actual progress via usr-meta.

**Comment by stevegrunwell** [comment]
Sounds great. I'll go ahead and track the last video, and I've opened #54 for a future phase.
