### ISSUE TITLE
Multiple Admin Messages Displayed when Key Saved

### ISSUE THREAD

**Issue by bswatson** [liquidweb/wp101plugin#59]
<img width="1737" alt="screen shot 2018-09-17 at 11 29 51 am" src="https://user-images.githubusercontent.com/303029/45633162-14ebcf00-ba6d-11e8-88f5-1f4ad07b5355.png">

**Comment by stevegrunwell** [comment]
It appears this was resolved as a side-effect of #68, which did a fair amount to cut down on unnecessary secondary requests.
