### ISSUE TITLE
Add-on Recommendation is already available

### ISSUE THREAD

**Issue by bswatson** [liquidweb/wp101plugin#60]
The recommended add-on provided in the Video Tutorials Add-ons section recommends the 22-part WooCommerce series.

<img width="594" alt="screen shot 2018-09-08 at 12 16 54 am" src="https://user-images.githubusercontent.com/303029/45250224-bd2ac680-b2fc-11e8-97e9-54c9e32ab31a.png">

This happens to be the video series that the customer already has available.

<img width="1740" alt="screen shot 2018-09-08 at 12 18 51 am" src="https://user-images.githubusercontent.com/303029/45250231-d5024a80-b2fc-11e8-86aa-e996b847a148.png">

**Comment by stevegrunwell** [comment]
This is more of a UX issue — the "Watch Videos" button is shown instead of "Get Series" (in blue) as an indication that the series is already available, but that's confusing when only one add-on is available for a given plan.
